import type { D1DatabaseLike } from "../adapters/d1-snapshot-store";
import { newId, nowIso } from "../domain/factories";
interface Statement{bind(...values:unknown[]):Statement;all<T>():Promise<{results:T[]}>;run():Promise<{success:boolean}>}
type Db={prepare(query:string):Statement}
export async function adminOverview(database:D1DatabaseLike){const db=database as unknown as Db;const [users,sessions,links,audit]=await Promise.all([
 db.prepare("SELECT user_id,email,display_name,global_role,status,created_at,last_seen_at FROM users ORDER BY created_at DESC LIMIT 250").all<Record<string,unknown>>(),
 db.prepare("SELECT s.session_id,s.user_id,u.email,s.created_at,s.expires_at,s.last_seen_at,s.revoked_at FROM sessions s JOIN users u ON u.user_id=s.user_id ORDER BY s.created_at DESC LIMIT 250").all<Record<string,unknown>>(),
 db.prepare("SELECT guest_link_id,workspace_id,role,created_at,expires_at,consumed_at,revoked_at FROM guest_links ORDER BY created_at DESC LIMIT 250").all<Record<string,unknown>>(),
 db.prepare("SELECT event_id,actor_user_id,action,target_type,target_id,detail_json,created_at FROM auth_audit_events ORDER BY created_at DESC LIMIT 250").all<Record<string,unknown>>()]);return{users:users.results,sessions:sessions.results,guestLinks:links.results,audit:audit.results}}
export async function audit(database:D1DatabaseLike,actor:string,action:string,targetType:string,targetId:string|null,detail:Record<string,unknown>={}){const db=database as unknown as Db;await db.prepare("INSERT INTO auth_audit_events(event_id,actor_user_id,action,target_type,target_id,detail_json,created_at) VALUES(?,?,?,?,?,?,?)").bind(newId("aud"),actor,action,targetType,targetId,JSON.stringify(detail),nowIso()).run()}
export async function adminMutation(database:D1DatabaseLike,actor:string,input:{action:string;targetId:string;value?:string}){const db=database as unknown as Db,now=nowIso();switch(input.action){case"user.role":if(!["admin","user"].includes(input.value??""))throw new Error("Invalid role");await db.prepare("UPDATE users SET global_role=?,updated_at=? WHERE user_id=?").bind(input.value,now,input.targetId).run();break;case"user.status":if(!["active","disabled"].includes(input.value??""))throw new Error("Invalid status");await db.prepare("UPDATE users SET status=?,updated_at=? WHERE user_id=?").bind(input.value,now,input.targetId).run();break;case"session.revoke":await db.prepare("UPDATE sessions SET revoked_at=? WHERE session_id=? AND revoked_at IS NULL").bind(now,input.targetId).run();break;case"guest.revoke":await db.prepare("UPDATE guest_links SET revoked_at=? WHERE guest_link_id=? AND revoked_at IS NULL").bind(now,input.targetId).run();break;default:throw new Error("Unsupported admin action")}await audit(database,actor,input.action,input.action.split(".")[0],input.targetId,{value:input.value})}
