import { createRemoteJWKSet, jwtVerify } from "jose";
import type { D1DatabaseLike } from "../adapters/d1-snapshot-store";
import { newId, nowIso } from "../domain/factories";
import type { RuntimeEnv } from "./runtime";

interface Statement { bind(...values: unknown[]): Statement; first<T>(): Promise<T|null>; run(): Promise<{success:boolean;meta?:{changes?:number}}> }
interface AuthDb extends D1DatabaseLike { prepare(query:string): Statement }
export interface SessionUser { userId:string; email:string; displayName:string; globalRole:"admin"|"user"; expiresAt:string }
export interface ProviderProfile { provider:string; subject:string; email:string; displayName:string }

function bytes(size=32){const b=new Uint8Array(size);crypto.getRandomValues(b);return b}
function token(size=32){return Array.from(bytes(size),b=>b.toString(16).padStart(2,"0")).join("")}
async function hash(value:string){const encoded=new TextEncoder().encode(value);return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",encoded)),b=>b.toString(16).padStart(2,"0")).join("")}
function normalize(email:string){return email.trim().toLowerCase()}
function adminEmails(env:RuntimeEnv){return new Set((env.AUTH_ADMIN_EMAILS??"").split(",").map(normalize).filter(Boolean))}

export function sessionCookie(raw:string,maxAge:number){return `stowplan_session=${raw}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
export function clearSessionCookie(){return "stowplan_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"}
export function cookieValue(request:Request,name:string){return request.headers.get("cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1)??null}

export async function createOrLinkUser(db:AuthDb,env:RuntimeEnv,profile:ProviderProfile):Promise<SessionUser>{
 const email=normalize(profile.email),now=nowIso();
 const existingIdentity=await db.prepare("SELECT u.user_id,u.email,u.display_name,u.global_role,u.status FROM identities i JOIN users u ON u.user_id=i.user_id WHERE i.provider=? AND i.provider_subject=?").bind(profile.provider,profile.subject).first<{user_id:string;email:string;display_name:string;global_role:"admin"|"user";status:string}>();
 if(existingIdentity){if(existingIdentity.status!=="active")throw new Error("Account is disabled");await db.prepare("UPDATE identities SET last_used_at=? WHERE provider=? AND provider_subject=?").bind(now,profile.provider,profile.subject).run();return {userId:existingIdentity.user_id,email:existingIdentity.email,displayName:existingIdentity.display_name,globalRole:existingIdentity.global_role,expiresAt:""}}
 let user=await db.prepare("SELECT user_id,email,display_name,global_role,status FROM users WHERE email=? COLLATE NOCASE").bind(email).first<{user_id:string;email:string;display_name:string;global_role:"admin"|"user";status:string}>();
 if(!user){const count=await db.prepare("SELECT COUNT(*) AS count FROM users").first<{count:number}>();const role=(count?.count===0||adminEmails(env).has(email))?"admin":"user";const id=newId("usr");await db.prepare("INSERT INTO users(user_id,email,display_name,global_role,status,created_at,updated_at,last_seen_at) VALUES(?,?,?,?, 'active',?,?,?)").bind(id,email,profile.displayName,role,now,now,now).run();user={user_id:id,email,display_name:profile.displayName,global_role:role,status:"active"}}
 if(user.status!=="active")throw new Error("Account is disabled");
 await db.prepare("INSERT INTO identities(identity_id,user_id,provider,provider_subject,email,created_at,last_used_at) VALUES(?,?,?,?,?,?,?)").bind(newId("idn"),user.user_id,profile.provider,profile.subject,email,now,now).run();
 return {userId:user.user_id,email:user.email,displayName:user.display_name,globalRole:user.global_role,expiresAt:""};
}

export async function issueSession(db:AuthDb,env:RuntimeEnv,user:SessionUser,request:Request,maximumSeconds?:number){const raw=token(),now=nowIso(),days=Math.max(1,Math.min(90,Number(env.AUTH_SESSION_DAYS??30))),maxAge=maximumSeconds??days*86400,end=new Date(Date.now()+maxAge*1000).toISOString();await db.prepare("INSERT INTO sessions(session_id,user_id,token_hash,created_at,expires_at,last_seen_at,user_agent,ip_prefix) VALUES(?,?,?,?,?,?,?,?)").bind(newId("ses"),user.userId,await hash(raw),now,end,now,request.headers.get("user-agent")?.slice(0,300)??null,request.headers.get("cf-connecting-ip")?.split(".").slice(0,3).join(".")??null).run();return {raw,maxAge}}
export async function authenticate(db:AuthDb,request:Request):Promise<SessionUser|null>{const raw=cookieValue(request,"stowplan_session");if(!raw)return null;const row=await db.prepare("SELECT u.user_id,u.email,u.display_name,u.global_role,u.status,s.expires_at FROM sessions s JOIN users u ON u.user_id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>?").bind(await hash(raw),nowIso()).first<{user_id:string;email:string;display_name:string;global_role:"admin"|"user";status:string;expires_at:string}>();if(!row||row.status!=="active")return null;return {userId:row.user_id,email:row.email,displayName:row.display_name,globalRole:row.global_role,expiresAt:row.expires_at}}
export async function revokeCurrentSession(db:AuthDb,request:Request){const raw=cookieValue(request,"stowplan_session");if(raw)await db.prepare("UPDATE sessions SET revoked_at=? WHERE token_hash=? AND revoked_at IS NULL").bind(nowIso(),await hash(raw)).run()}
export async function canWriteWorkspace(db:AuthDb,userId:string,workspaceId:string){const row=await db.prepare("SELECT role FROM workspace_members WHERE workspace_id=? AND user_id=?").bind(workspaceId,userId).first<{role:string}>();return row?.role==="owner"||row?.role==="editor"}
export async function claimWorkspace(db:AuthDb,userId:string,workspaceId:string){await db.prepare("INSERT OR IGNORE INTO workspace_members(workspace_id,user_id,role,created_at) VALUES(?,?, 'owner',?)").bind(workspaceId,userId,nowIso()).run()}
export async function createGuestLink(db:AuthDb,workspaceId:string,creator:string,role:"editor"|"viewer",hours=24){const raw=token(),id=newId("guest"),now=nowIso(),end=new Date(Date.now()+Math.max(1,Math.min(168,hours))*3_600_000).toISOString();await db.prepare("INSERT INTO guest_links(guest_link_id,workspace_id,created_by_user_id,token_hash,role,created_at,expires_at) VALUES(?,?,?,?,?,?,?)").bind(id,workspaceId,creator,await hash(raw),role,now,end).run();return{id,raw,expiresAt:end}}
export async function consumeGuestLink(db:AuthDb,env:RuntimeEnv,raw:string,request:Request){const now=nowIso(),row=await db.prepare("SELECT guest_link_id,workspace_id,role,expires_at FROM guest_links WHERE token_hash=? AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at>?").bind(await hash(raw),now).first<{guest_link_id:string;workspace_id:string;role:"editor"|"viewer";expires_at:string}>();if(!row)throw new Error("Guest link is invalid, expired, used, or revoked");const userId=newId("usr"),email=`guest+${row.guest_link_id}@stowplan.invalid`;await db.prepare("INSERT INTO users(user_id,email,display_name,global_role,status,created_at,updated_at,last_seen_at) VALUES(?,?, 'Guest', 'user', 'active',?,?,?)").bind(userId,email,now,now,now).run();await db.prepare("INSERT INTO identities(identity_id,user_id,provider,provider_subject,email,created_at,last_used_at) VALUES(?,?, 'guest',?,?,?,?)").bind(newId("idn"),userId,row.guest_link_id,email,now,now).run();await db.prepare("INSERT INTO workspace_members(workspace_id,user_id,role,created_at) VALUES(?,?,?,?)").bind(row.workspace_id,userId,row.role,now).run();await db.prepare("UPDATE guest_links SET consumed_at=? WHERE guest_link_id=? AND consumed_at IS NULL").bind(now,row.guest_link_id).run();const maxAge=Math.max(60,Math.min(86400,Math.floor((Date.parse(row.expires_at)-Date.now())/1000)));const session=await issueSession(db,env,{userId,email,displayName:"Guest",globalRole:"user",expiresAt:row.expires_at},request,maxAge);return{session,workspaceId:row.workspace_id}}

export interface OAuthProvider { id:"google"|"github"; authorizationUrl:string; tokenUrl:string; scopes:string; clientId:string; clientSecret:string }
export function provider(env:RuntimeEnv,id:string):OAuthProvider|null {if(id==="google"&&env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET)return{id,authorizationUrl:"https://accounts.google.com/o/oauth2/v2/auth",tokenUrl:"https://oauth2.googleapis.com/token",scopes:"openid email profile",clientId:env.GOOGLE_CLIENT_ID,clientSecret:env.GOOGLE_CLIENT_SECRET};if(id==="github"&&env.GITHUB_CLIENT_ID&&env.GITHUB_CLIENT_SECRET)return{id,authorizationUrl:"https://github.com/login/oauth/authorize",tokenUrl:"https://github.com/login/oauth/access_token",scopes:"read:user user:email",clientId:env.GITHUB_CLIENT_ID,clientSecret:env.GITHUB_CLIENT_SECRET};return null}
function b64url(data:Uint8Array){return btoa(String.fromCharCode(...data)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
export async function beginOAuth(db:AuthDb,p:OAuthProvider,base:string,returnTo:string){const state=token(),verifier=b64url(bytes(48)),challenge=b64url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier)))),end=new Date(Date.now()+10*60_000).toISOString();await db.prepare("INSERT INTO oauth_states(state_hash,provider,verifier_ciphertext,return_to,created_at,expires_at) VALUES(?,?,?,?,?,?)").bind(await hash(state),p.id,verifier,returnTo,nowIso(),end).run();const u=new URL(p.authorizationUrl);u.searchParams.set("client_id",p.clientId);u.searchParams.set("redirect_uri",`${base}/api/auth/${p.id}/callback`);u.searchParams.set("response_type","code");u.searchParams.set("scope",p.scopes);u.searchParams.set("state",state);u.searchParams.set("code_challenge",challenge);u.searchParams.set("code_challenge_method","S256");return u.toString()}
export async function finishOAuth(db:AuthDb,p:OAuthProvider,base:string,state:string,code:string):Promise<{profile:ProviderProfile;returnTo:string}>{const row=await db.prepare("SELECT verifier_ciphertext,return_to FROM oauth_states WHERE state_hash=? AND provider=? AND consumed_at IS NULL AND expires_at>?").bind(await hash(state),p.id,nowIso()).first<{verifier_ciphertext:string;return_to:string}>();if(!row)throw new Error("OAuth state is invalid or expired");await db.prepare("UPDATE oauth_states SET consumed_at=? WHERE state_hash=?").bind(nowIso(),await hash(state)).run();const body=new URLSearchParams({client_id:p.clientId,client_secret:p.clientSecret,code,redirect_uri:`${base}/api/auth/${p.id}/callback`,code_verifier:row.verifier_ciphertext,grant_type:"authorization_code"});const tokenResponse=await fetch(p.tokenUrl,{method:"POST",headers:{accept:"application/json","content-type":"application/x-www-form-urlencoded"},body});if(!tokenResponse.ok)throw new Error("OAuth token exchange failed");const tokens=await tokenResponse.json() as {access_token?:string;id_token?:string};if(p.id==="google"){if(!tokens.id_token)throw new Error("Google did not return an ID token");const jwks=createRemoteJWKSet(new URL("https://www.googleapis.com/oauth2/v3/certs"));const {payload}=await jwtVerify(tokens.id_token,jwks,{audience:p.clientId,issuer:["https://accounts.google.com","accounts.google.com"]});const email=String(payload.email??"");if(!payload.sub||!email)throw new Error("Google identity lacks required claims");return{profile:{provider:p.id,subject:payload.sub,email,displayName:String(payload.name??email)},returnTo:row.return_to}}if(!tokens.access_token)throw new Error("GitHub did not return an access token");const headers={authorization:`Bearer ${tokens.access_token}`,accept:"application/vnd.github+json","user-agent":"Stowplan"};const [account,emails]=await Promise.all([fetch("https://api.github.com/user",{headers}).then(r=>r.json()) as Promise<{id:number;login:string;name?:string;email?:string}>,fetch("https://api.github.com/user/emails",{headers}).then(r=>r.json()) as Promise<{email:string;primary:boolean;verified:boolean}[]>]);const email=account.email??emails.find(x=>x.primary&&x.verified)?.email??emails.find(x=>x.verified)?.email;if(!email)throw new Error("GitHub account has no verified email");return{profile:{provider:p.id,subject:String(account.id),email,displayName:account.name??account.login},returnTo:row.return_to}}
export async function verifyAccess(env:RuntimeEnv,assertion:string):Promise<ProviderProfile>{if(!env.CLOUDFLARE_ACCESS_TEAM_DOMAIN||!env.CLOUDFLARE_ACCESS_AUD)throw new Error("Cloudflare Access is not configured");const domain=env.CLOUDFLARE_ACCESS_TEAM_DOMAIN.replace(/^https?:\/\//,"").replace(/\/$/,"");const jwks=createRemoteJWKSet(new URL(`https://${domain}/cdn-cgi/access/certs`));const {payload}=await jwtVerify(assertion,jwks,{audience:env.CLOUDFLARE_ACCESS_AUD,issuer:`https://${domain}`});const email=String(payload.email??"");if(!payload.sub||!email)throw new Error("Access assertion lacks identity claims");return{provider:"cloudflare-access",subject:payload.sub,email,displayName:String(payload.name??email)}}
