"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
interface Overview { users:Record<string,unknown>[]; sessions:Record<string,unknown>[]; guestLinks:Record<string,unknown>[]; audit:Record<string,unknown>[] }
export default function AdminPage(){
 const[data,setData]=useState<Overview|null>(null),[error,setError]=useState("");
 const load=useCallback(()=>{void fetch("/api/admin/overview",{cache:"no-store"}).then(async response=>{const body=await response.json() as Overview&{error?:string};if(!response.ok)throw new Error(body.error);setData(body)}).catch(reason=>setError(reason instanceof Error?reason.message:"Could not load admin data"))},[]);
 useEffect(()=>load(),[load]);
 const mutate=async(action:string,targetId:string,value?:string)=>{const response=await fetch("/api/admin/mutate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,targetId,value})});if(!response.ok){const body=await response.json() as {error?:string};setError(body.error??"Admin mutation failed")}else load()};
 return <main className="admin-page"><header><div><p className="eyebrow">Server-enforced control plane</p><h1>Stowplan administration</h1></div><Link href="/">Back to organizer</Link></header>{error&&<div className="admin-error">{error}</div>}{!data&&!error&&<p>Loading administrative records…</p>}{data&&<><section><h2>Users <small>{data.users.length}</small></h2><div className="admin-table">{data.users.map(u=><div key={String(u.user_id)}><span><strong>{String(u.display_name)}</strong><small>{String(u.email)}</small></span><select aria-label={`Role for ${String(u.email)}`} value={String(u.global_role)} onChange={e=>mutate("user.role",String(u.user_id),e.target.value)}><option>user</option><option>admin</option></select><button onClick={()=>mutate("user.status",String(u.user_id),u.status==="active"?"disabled":"active")}>{u.status==="active"?"Disable":"Enable"}</button></div>)}</div></section><section><h2>Sessions <small>{data.sessions.length}</small></h2><div className="admin-table">{data.sessions.map(s=><div key={String(s.session_id)}><span><strong>{String(s.email)}</strong><small>Expires {new Date(String(s.expires_at)).toLocaleString()}</small></span><b>{s.revoked_at?"revoked":"active"}</b><button disabled={!!s.revoked_at} onClick={()=>mutate("session.revoke",String(s.session_id))}>Revoke</button></div>)}</div></section><section><h2>Guest links <small>{data.guestLinks.length}</small></h2><div className="admin-table">{data.guestLinks.map(g=><div key={String(g.guest_link_id)}><span><strong>{String(g.role)} · {String(g.workspace_id)}</strong><small>Expires {new Date(String(g.expires_at)).toLocaleString()}</small></span><b>{g.revoked_at?"revoked":g.consumed_at?"used":"available"}</b><button disabled={!!g.revoked_at} onClick={()=>mutate("guest.revoke",String(g.guest_link_id))}>Revoke</button></div>)}</div></section><section><h2>Auth audit <small>{data.audit.length}</small></h2><div className="admin-table">{data.audit.map(a=><div key={String(a.event_id)}><span><strong>{String(a.action)}</strong><small>{new Date(String(a.created_at)).toLocaleString()} · {String(a.target_type)}</small></span></div>)}</div></section></>}</main>
}
