"use client";

import { useEffect, useState } from "react";
import { Activity, Boxes, ClipboardList, Map, Moon, PackagePlus, Search, Settings, Sun, Undo2, Wifi, WifiOff } from "lucide-react";
import { createDemoState } from "../domain/demo";
import { createEmptyState, createItem, createLocation } from "../domain/factories";
import { generatePlan as buildMovePlan } from "../domain/planner";
import type { Command, Location, ThemePreference, WorkspaceState } from "../domain/types";
import { StowplanProvider, useStowplan } from "./store";

type View = "capture" | "spaces" | "inventory" | "plan" | "activity" | "settings";
const nav: {id:View;label:string;icon:typeof Boxes}[]=[
  {id:"capture",label:"Capture",icon:PackagePlus},{id:"spaces",label:"Spaces",icon:Map},{id:"inventory",label:"Inventory",icon:Boxes},
  {id:"plan",label:"Plan",icon:ClipboardList},{id:"activity",label:"Activity",icon:Activity},{id:"settings",label:"Settings",icon:Settings},
];

export function StowplanApp(){return <StowplanProvider><Application/></StowplanProvider>}
function Application(){
 const {state,initialize,dispatch,replace,online,pending,syncing}=useStowplan(); const [view,setView]=useState<View>("capture"); const [selected,setSelected]=useState<string|null>(null); const [theme,setTheme]=useState<ThemePreference>("system");
 useEffect(()=>{queueMicrotask(()=>{const saved=localStorage.getItem("stowplan-theme") as ThemePreference|null;if(saved)setTheme(saved)});if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
 useEffect(()=>{const dark=theme==="dark"||(theme==="system"&&matchMedia("(prefers-color-scheme:dark)").matches);document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("stowplan-theme",theme)},[theme]);
 if(!state)return <Onboarding onStart={async demo=>{const next=demo?createDemoState():createEmptyState();await initialize(next);setSelected(next.locations[0]?.id??null)}}/>;
 const current=state.locations.find(x=>x.id===selected)??state.locations.find(x=>!x.archivedAt)??null;
 return <div className="app-shell"><aside><Brand/><nav>{nav.map(x=><Nav key={x.id} {...x} active={x.id===view} select={()=>setView(x.id)}/>)}</nav><div className="sync">{online?<Wifi/>:<WifiOff/>}<span>{syncing?"Backing up…":pending?`${pending} saved on device`:online?"Up to date":"Working offline"}</span></div></aside><main><header><div><p className="eyebrow">{state.workspace.name}</p><h1>{nav.find(x=>x.id===view)?.label}</h1></div><button className="icon" aria-label="Change theme" onClick={()=>setTheme(theme==="system"?"dark":theme==="dark"?"light":"system")}>{theme==="dark"?<Moon/>:<Sun/>}</button></header>
 {view==="capture"&&<Capture state={state} current={current} select={setSelected} commit={dispatch}/>} {view==="spaces"&&<Spaces state={state} current={current} select={setSelected} commit={dispatch}/>} {view==="inventory"&&<Inventory state={state} commit={dispatch}/>} {view==="plan"&&<Planner state={state} commit={dispatch}/>} {view==="activity"&&<History state={state} commit={dispatch}/>} {view==="settings"&&<Preferences state={state} theme={theme} setTheme={setTheme} replace={replace}/>}</main><nav className="bottom">{nav.slice(0,5).map(x=><Nav key={x.id} {...x} active={x.id===view} select={()=>setView(x.id)}/>)}</nav></div>
}
function Brand(){return <div className="brand"><b>S</b><span><strong>Stowplan</strong><small>Know where everything lives</small></span></div>}
function Nav({label,icon:Icon,active,select}:{label:string;icon:typeof Boxes;active:boolean;select:()=>void}){return <button className="nav" data-active={active} onClick={select}><Icon/><span>{label}</span></button>}
function Onboarding({onStart}:{onStart:(demo:boolean)=>void}){return <main className="onboarding"><section><Brand/><p className="eyebrow">A calmer first pass</p><h1>Label it. Count it.<br/>Find it later.</h1><p>Start with one box, drawer, or cabinet. Stowplan remembers nested containers and keeps working without connectivity or a healthy server.</p><div className="steps"><span><b>1</b>Label a space</span><span><b>2</b>Add what is inside</span><span><b>3</b>Mark it counted</span></div><button className="primary" onClick={()=>onStart(false)}>Start my workspace</button><button className="linkish" onClick={()=>onStart(true)}>Explore the kitchen demo instead</button><small>Your inventory is saved on this device first.</small></section></main>}

function Capture({state,current,select,commit}:{state:WorkspaceState;current:Location|null;select:(id:string)=>void;commit:(c:Command)=>void}){
 const live=state.locations.filter(l=>!l.archivedAt),done=live.filter(l=>["counted","known_empty"].includes(l.captureStatus)).length,items=current?state.items.filter(i=>i.locationId===current.id&&!i.archivedAt):[];
 const addContainer=(fd:FormData)=>commit({type:"location.create",location:createLocation({code:String(fd.get("code")),name:String(fd.get("name")),kind:current?"container":"room",parentId:current?.id??null})});
 return <div className="content capture"><section className="panel queue"><div className="title"><div><p className="eyebrow">First-pass coverage</p><h2>{done} of {live.length} checked</h2></div><b>{live.length-done} left</b></div><div className="progress"><i style={{width:`${live.length?done/live.length*100:0}%`}}/></div>{live.map(l=><button key={l.id} data-active={current?.id===l.id} onClick={()=>select(l.id)}><span><b>{l.code}</b>{l.name}</span><small>{l.captureStatus.replace("_"," ")}</small></button>)}<form action={addContainer} className="nested"><input required name="code" placeholder="Label code"/><input required name="name" placeholder={current?"Nested box or bin":"First room or area"}/><button>{current?"Add inside":"Add space"}</button></form></section><section className="panel capture-card">{current?<><div className="title"><div><p className="eyebrow">Inside</p><h2>{current.code} · {current.name}</h2></div><span className="tag">{current.captureStatus.replace("_"," ")}</span></div><form className="quick" action={fd=>commit({type:"item.create",item:createItem({locationId:current.id,name:String(fd.get("name")),quantity:Number(fd.get("quantity")),unit:String(fd.get("unit"))})})}><label>Qty<input required type="number" min="0.01" step="any" name="quantity" defaultValue="1"/></label><label>Unit<select name="unit"><option>each</option><option>boxes</option><option>bags</option><option>cans</option><option>pairs</option></select></label><label className="grow">What is it?<input required name="name" placeholder="e.g. winter gloves"/></label><button className="primary">Save & add next</button></form><div className="captured">{items.map(i=><div key={i.id}><b>{i.quantity} {i.unit}</b><strong>{i.name}</strong></div>)}{!items.length&&<Empty title="Nothing recorded yet" text="Add an item, or mark this space as known empty."/>}</div><div className="finish"><button onClick={()=>commit({type:"capture.status",id:current.id,status:"known_empty"})}>Known empty</button><button className="primary" onClick={()=>commit({type:"capture.status",id:current.id,status:"counted"})}>Mark counted & next</button></div></>:<Empty title="Add your first space" text="Give a room, cabinet, box, or drawer the same code as its physical label."/>}</section></div>
}

function Spaces({state,current,select,commit}:{state:WorkspaceState;current:Location|null;select:(id:string)=>void;commit:(c:Command)=>void}){const branch=(p:string|null,d=0):React.ReactNode=>state.locations.filter(l=>l.parentId===p&&!l.archivedAt).sort((a,b)=>a.order-b.order).map(l=><div key={l.id}><button className="tree-row" data-active={current?.id===l.id} style={{paddingLeft:16+d*20}} onClick={()=>select(l.id)}><b>{l.code}</b><span>{l.name}</span><small>{state.items.filter(i=>i.locationId===l.id).length}</small></button>{branch(l.id,d+1)}</div>);return <div className="content split"><section className="panel"><div className="title"><h2>Location tree</h2></div>{branch(null)}</section><section className="panel inspector">{current?<><p className="eyebrow">{current.kind}</p><h2>{current.name}</h2><p className="muted">Label {current.code} · {state.items.filter(i=>i.locationId===current.id).length} item records</p><div className="conditions">{Object.entries(current.conditions).map(([k,v])=><span key={k}><small>{k}</small><b>{String(v)}</b></span>)}</div><label>Description<textarea defaultValue={current.description} onBlur={e=>commit({type:"location.update",id:current.id,changes:{description:e.target.value}})}/></label><button className="danger" onClick={()=>commit({type:"location.archive",id:current.id,archived:true})}>Archive location</button></>:<Empty title="Select a space" text="Its suitability and contents will appear here."/>}</section></div>}

function Inventory({state,commit}:{state:WorkspaceState;commit:(c:Command)=>void}){const[q,setQ]=useState("");const[selected,setSelected]=useState<string[]>([]);const shown=state.items.filter(i=>!i.archivedAt&&[i.name,i.category,...i.tags].join(" ").toLowerCase().includes(q.toLowerCase()));return <div className="content"><div className="toolbar"><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search names, categories, and tags"/></label><span>{shown.length} records</span></div><section className="panel inventory">{shown.map(i=>{const l=state.locations.find(x=>x.id===i.locationId);return <div key={i.id}><input aria-label={`Select ${i.name}`} type="checkbox" checked={selected.includes(i.id)} onChange={()=>setSelected(s=>s.includes(i.id)?s.filter(x=>x!==i.id):[...s,i.id])}/><span><strong>{i.name}</strong><small>{i.category} · {i.frequency}</small></span><b>{i.quantity} {i.unit}</b><span>{l?.code} · {l?.name}</span></div>})}</section>{selected.length>0&&<div className="floating"><b>{selected.length} selected</b><select aria-label="Move selected items" onChange={e=>{if(e.target.value){commit({type:"item.bulkMove",itemIds:selected,destinationId:e.target.value});setSelected([])}}}><option value="">Move to…</option>{state.locations.map(l=><option value={l.id} key={l.id}>{l.code} · {l.name}</option>)}</select></div>}</div>}

function Planner({state,commit}:{state:WorkspaceState;commit:(c:Command)=>void}){const active=state.plans.find(p=>p.status==="active");return <div className="content"><section className="panel hero"><p className="eyebrow">Explainable recommendations</p><h2>Fewer moves, better homes.</h2><p>Balance suitability, access, grouping, capacity, and move cost—including moving a whole nested box when that is simpler.</p><button className="primary" onClick={()=>commit({type:"plan.create",plan:buildMovePlan(state,{name:"Suggested reset"})})}>Generate move plan</button></section>{active?<section className="panel plan-list">{active.steps.map((s,n)=><div key={s.id} data-done={!!s.completedAt}><i>{n+1}</i><span><strong>{s.type==="location"?"Move container":"Move item"}</strong><small>{s.explanation.join(" · ")}</small></span><b>{state.locations.find(l=>l.id===s.sourceId)?.code} → {state.locations.find(l=>l.id===s.destinationId)?.code}</b><button disabled={!!s.completedAt} onClick={()=>commit({type:"plan.step.complete",planId:active.id,stepId:s.id})}>{s.completedAt?"Done":"Complete"}</button></div>)}</section>:<Empty title="No active plan" text="Generate one after your first-pass count is reasonably complete."/>}</div>}

function History({state,commit}:{state:WorkspaceState;commit:(c:Command)=>void}){return <div className="content"><div className="toolbar"><span>{state.activities.length} recorded changes</span><div><button onClick={()=>commit({type:"history.batchUndo",count:5})}>Undo 5</button><button onClick={()=>commit({type:"history.batchRedo",count:5})}>Redo 5</button></div></div><section className="panel history">{[...state.activities].reverse().map(a=><div key={a.id}><Undo2/><span><strong>{a.label}</strong><small>{new Date(a.timestamp).toLocaleString()} · {a.patches.length} fields</small></span><b>{a.status}</b><button onClick={()=>commit(a.status==="applied"?{type:"history.undo",activityId:a.id}:{type:"history.reapply",activityId:a.id})}>{a.status==="applied"?"Undo this":"Reapply"}</button></div>)}{!state.activities.length&&<Empty title="No changes yet" text="Every meaningful change will be inspectable and reversible here."/>}</section></div>}

function Preferences({state,theme,setTheme,replace}:{state:WorkspaceState;theme:ThemePreference;setTheme:(t:ThemePreference)=>void;replace:(s:WorkspaceState)=>void}){const download=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download=`stowplan-${state.workspace.id}.json`;a.click()};return <div className="content settings"><section className="panel"><h2>Appearance</h2><div className="segments">{(["system","light","dark"] as const).map(t=><button data-active={theme===t} key={t} onClick={()=>setTheme(t)}>{t}</button>)}</div><h2>Backup & recovery</h2><p className="muted">Export a complete portable snapshot. Imports remain local until you review and synchronize.</p><button onClick={download}>Export JSON backup</button><label className="file">Import backup<input type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(f)replace(JSON.parse(await f.text()))}}/></label></section><section className="panel"><h2>Help & source</h2><a href="/docs/">Read the documentation</a><a target="_blank" rel="noreferrer" href={process.env.NEXT_PUBLIC_REPOSITORY_URL||"https://github.com/j-256/stowplan"}>View source repository</a><p className="license">AGPL-3.0-only<br/>Copyright © 2026 James Klein (j-256)</p></section></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><b>□</b><h3>{title}</h3><p>{text}</p></div>}
